export enum AvailableDatabases {
    RESULTS = 'RESULTS',
    KNOWLEDGE = 'KNOWLEDGE',
    PLUGINS = 'PLUGINS'
}

export enum AvailableCollections {
    SBOM_SERVICE = 'SBOMS',
    PATCHING_SERVICE = 'PATCHES',
    VULNERABILITIES_SERVICE = 'VULNERABILITIES',
    LICENSES_SERVICE = 'LICENSES',

    PROJECTS = 'PROJECTS',
    ORGANIZATIONS_PROJECTS_EDGES = 'ORGANIZATIONS_PROJECTS_EDGES',

    ANALYSES = 'ANALYSES',
    PROJECT_ANALYSES_EDGES = 'PROJECT_ANALYSES_EDGES',

    ORGANIZATIONS = 'ORGANIZATIONS',
    ORGANIZATIONS_AUDIT_LOGS = 'ORGANIZATIONS_AUDIT_LOGS',
    ORGANIZATIONS_INVITATIONS = 'ORGANIZATIONS_INVITATIONS',

    INTEGRATIONS = 'INTEGRATIONS',
    ORGANIZATIONS_INTEGRATIONS_EDGES = 'ORGANIZATIONS_INTEGRATIONS_EDGES',

    ANALYZERS = 'ANALYZERS',
    ORGANIZATIONS_ANALYZERS_EDGES = 'ORGANIZATIONS_ANALYZERS_EDGES',

    POLICIES = 'POLICIES',
    ORGANIZATIONS_POLICIES_EDGES = 'ORGANIZATIONS_POLICIES_EDGES',

    USERS = 'USERS',
    USERS_PASSWORD_RESET_REQUESTS = 'USERS_PASSWORD_RESET_REQUESTS',
    USERS_REGISTRATION_VERIFICATION = 'USERS_REGISTRATION_VERIFICATION',
    ORGANIZATIONS_USERS_EDGES = 'ORGANIZATIONS_USERS_EDGES',
    SOCIAL_REGISTRATION_TEMP = 'SOCIAL_REGISTRATION_TEMP',

    EMAIL_UNSUBSCRIPTIONS = 'EMAIL_UNSUBSCRIPTIONS',
    EMAIL_UNSUBSCRIBE_ACTIONS = 'EMAIL_UNSUBSCRIPTIONS_ACTIONS',

    GITHUB_REPOS_CACHE = 'GITHUB_REPOS_CACHE',
    GITHUB_REPOS_CACHE_META = 'GITHUB_REPOS_CACHE_META',

    GITLAB_REPOS_CACHE = 'GITLAB_REPOS_CACHE',
    GITLAB_REPOS_CACHE_META = 'GITLAB_REPOS_CACHE_META',

    APIKEYS = 'API_KEYS',
    APIKEYS_USER_EDGES = 'API_KEYS_USER_EDGES',
    APIKEYS_USAGE_LOGS = 'API_KEYS_USAGE_LOGS',

    RESULTS_EDGES = 'RESULTS_EDGES',

    NOTIFICATIONS = 'NOTIFICATIONS',
    USER_NOTIFICATIONS_EDGES = 'USER_NOTIFICATIONS_EDGES'
}

export enum AvailableGraphs {
    PROJECT_ANALYSIS_GRAPH = 'PROJECT_ANALYSIS_GRAPH',
    APIKEY_USER_GRAPH = 'API_KEY_USER_GRAPH',
    ORG_ANALYZER_GRAPH = 'ORG_ANALYZER_GRAPH',
    ORG_INTEGRATIONS_GRAPH = 'ORG_INTEGRATIONS_GRAPH',
    ORG_MEMBERSHIP_GRAPH = 'ORG_MEMBERSHIP_GRAPH',
    ORG_POLICIES_GRAPH = 'ORG_POLICIES_GRAPH',
    ORG_PROJECT_GRAPH = 'ORG_PROJECT_GRAPH',
    DEPENDENCIES_GRAPH = 'DEPENDENCIES_GRAPH',
    USER_NOTIFICATIONS_GRAPH = 'USER_NOTIFICATIONS_GRAPH'
}
