name: CodeClarity

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

# permissions:
#   contents: read

jobs:
  codeclarity-action:
    name: CodeClarity Actions
    runs-on: ubuntu-latest
    env:
      EMAIL: ${{ secrets.CODECLARITY_EMAIL }}
      PASSWORD: ${{ secrets.CODECLARITY_PASSWORD }}
      DOMAIN: ${{ secrets.CODECLARITY_DOMAIN }}

    steps:
      - name: Extract branch name
        shell: bash
        run:
          echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >>
          $GITHUB_OUTPUT
        id: extract_branch

      - name: Start Analysis
        uses: CodeClarityCE/codeclarity-action@v0
        with:
          branch: ${{ steps.extract_branch.outputs.branch }}
          projectName: ${{ github.repository }}
          analyzerName: 'JS Analyser'