name: CodeClarity

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

# permissions:
#   contents: read

jobs:
  codeclarity-action:
    name: CodeClarity Actions
    runs-on: ubuntu-latest
    env:
      EMAIL: ${{ secrets.CODECLARITY_EMAIL }}
      PASSWORD: ${{ secrets.CODECLARITY_PASSWORD }}
      DOMAIN: ${{ secrets.CODECLARITY_DOMAIN }}

    steps:
      - name: Start Analysis
        uses: CodeClarityCE/codeclarity-action@v0
        with:
          branch: 'main'
          projectName: 'parithera/api'
          analyzerName: 'JS Analyser'